FROM gradle:jdk17-alpine AS builder
WORKDIR /app
COPY . .
RUN gradle clean bootJar

FROM eclipse-temurin:17-jre-alpine AS runner
WORKDIR /app

ARG SPOTIFY_CLIENT_ID
ENV SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}

ARG SPOTIFY_CLIENT_SECRET
ENV SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}

ARG SPOTIFY_REDIRECT_URL
ENV SPOTIFY_REDIRECT_URL=${SPOTIFY_REDIRECT_URL}

ARG SPRING_DATASOURCE_URL
ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}

ARG SPRING_DATASOURCE_USERNAME
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}

ARG SPRING_DATASOURCE_PASSWORD
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}

COPY --from=builder /app/build/libs/*.jar app.jar
EXPOSE 8080

FROM runner AS runner_actions
CMD ["java", "-jar", "app.jar"]